version: '3.8'

services:
  fastapi-server:
    build: ./fastapi-server
    container_name: zoopjobs-fastapi-server
    ports:
      - "8028:8028"
    volumes:
      - ./fastapi-server:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zoopjobs
    depends_on:
      - db

  react-app:
    build: ./react-app
    container_name: zoopjobs-react-app
    ports:
      - "3028:3028"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8028
    depends_on:
      - fastapi-server

  db:
    image: postgres:15
    container_name: zoopjobs-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zoopjobs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 