version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zoopjobs
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db

  frontend:
    build: ./frontend/react-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react-app:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zoopjobs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 